import 'package:flutter/material.dart';
import 'package:flutterapp/test_20rice_20cardapp/generatedricecardwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/test_20rice_20cardapp/generatedricecardwidget/generated/GeneratedChinesericeWidget.dart';

/* Group Rice card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRicecardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 194.0,
      height: 286.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 194.0,
              height: 286.0,
              child: GeneratedChinesericeWidget(),
            ),
            Positioned(
              left: 13.0,
              top: 240.0,
              right: null,
              bottom: null,
              width: 167.0,
              height: 34.0,
              child: GeneratedGroup1Widget(),
            )
          ]),
    ));
  }
}
